CREATE TABLE [dbo].[meta]
(
    [Id] BIGINT IDENTITY(1,1) NOT NULL,
	[KeyId] BIGINT NOT NULL,
	[NamespaceId] BIGINT NOT NULL,
	[Value] sQL_VARIANT NULL,
	CONSTRAINT [PK_META] PRIMARY KEY CLUSTERED
	(
		[Id] ASC
	) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 1) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[meta]  WITH CHECK ADD  CONSTRAINT [FK_meta_ns] FOREIGN KEY([NamespaceId])
REFERENCES [dbo].[namespaces] ([Id])
GO

ALTER TABLE [dbo].[meta]  WITH CHECK ADD  CONSTRAINT [FK_meta_k] FOREIGN KEY([KeyId])
REFERENCES [dbo].[keys] ([Id])
GO

CREATE INDEX IX_meta_KeyId ON [dbo].[meta] ([KeyId]);
GO

CREATE INDEX IX_meta_NamespaceId ON [dbo].[meta] ([NamespaceId]);
GO
